# application.properties
spring.application.name=sport-ecom
spring.mongodb.uri=mongodb://localhost:27017/EliteGear
# For MongoDB Atlas (cloud): spring.data.mongodb.uri=mongodb+srv://user:pass@cluster0.mongodb.net/EliteGear

server.port=8080